### ISSUE TITLE
Working parcel as public server it complains about CORS policy

### ISSUE THREAD

**Issue by jespa007** [visualcamp/seeso-sample-web#2]
I'd like to start seeso-sample-web in order to test in my phone/tablet. To do that, I have to start parcel with my public IP

For example my ip is 192.168.1.133, so in the `package.json` I've added --host 192.168.1.133 option in the `gaze` script configuration,

```
{
  "name": "SeeSoWebSample",
  "version": "0.0.1",
  "description": "",
  "keywords": "",
  "license": "",
  "author": "",
  "scripts": {
    "gaze": "NODE_ENV=development parcel samples/gaze/index.html --open --port 8082 --host 192.168.1.133",
  },
  "devDependencies": {
    "parcel-bundler": "^1.12.4"
  },
  "dependencies": {
    "seeso": "^0.1.3",
    "wasm-check": "^2.0.1"
  }
}
```

It opens the browser but it complains about CORS policy,

![image](https://user-images.githubusercontent.com/7852409/119542678-19c1be80-bd90-11eb-871d-a6da9ef50d2a.png)

Is there a tip how to solve this issue ? I suspect that it has to add some information in the header in order to allow comunication throught different domains.

**Comment by aurian89** [comment]
CORS policy error is caused by  "SeeSo development/production key".

In our server, we check "key" and "domain" to activate SeeSo API.

To use "SeeSo development key" to run SeeSo web SDK, you need to:
    a. use "localhost:xxxx" or
    b. use ip address

If you want to use "https://development.bgaze.com:8083" or other domain, you need to use "SeeSo Production key".

**Comment by jespa007** [comment]
Thanks for your response @aurian89

I've created product key in seeso.io (the one that starts with prod_xxxx),

![image](https://user-images.githubusercontent.com/7852409/120172962-d8a03300-c203-11eb-8a19-34cc4850236b.png)


Still I'm getting the CORS policy,

![image](https://user-images.githubusercontent.com/7852409/119981457-f2503900-bfbd-11eb-9f40-3969bc5cb182.png)

In the index.js I have put the license key as the same in the console.seeso.io,

![image](https://user-images.githubusercontent.com/7852409/120173043-f1104d80-c203-11eb-9ebb-7cbaafb7e2cc.png)

**Comment by lackhole** [comment]
@jespa007 
Is your website https?
And you should avoid showing your license key at here, since this is a public repository.

**Comment by lackhole** [comment]
@jespa007 
Thankyou for using our SDK.
Can you check if your website is https?
We'll take a closer look on the next weekday.
And you should avoid showing your license key at here, since this issue is open to public.

**Comment by jespa007** [comment]
@lackhole thanks for your comment. You are right, I shouldn't put the key here. I'll reissue a new product key.
As you can see in my last response, the test is done using a https but at port 8083 without certificate. 
Also I'm running development.bgaze.com in the local net (not public) just only to test. So, as far as I can understant, the service has to be visible on internet in order to validate the key with console.seeso.io, right ?

**Comment by leeyongeun9** [comment]
@jespa007 
We need to detect the development state of the web service to manage the number of sessions.
The way we detect the state is website address.

If the base url of the website is an ip address or 'localhost', we consider it to be a development stste, otherwise, if the base url is in the form of a domain, it is regarded as a production state.
With development state there is no issue with CORS, but you have to consider CORS issue when you make public web service(see https://docs.seeso.io/docs/cross-origin-isolation/)

So, if you are currently in development process, **Use the IP address instead of development.bgaze.com and use the development key as the license key**.

Otherwise we haven't yet tested using a domain name in a local net. 
The above solution(ip address + dev key) will solve the problem, but for the connection with a domain in local net, we will tell you if such a connection method is possible and how to do it if possible.

**Comment by jespa007** [comment]
@YongEun-vc thanks for the response.  I've put my application at our server and init Seeso with product key but still I get CORS policy issue. The App runs Nodejs service at https://bgaze.com:8083. In the console.seeso.io I've only put the domain without specifiing port ... At console.seeso.io, Do I have to put also the port on production key (i.e https://bgaze.com:8083 ?)

![image](https://user-images.githubusercontent.com/7852409/120172171-0d5fba80-c203-11eb-8485-b54fc7e13ae0.png)

**Comment by leeyongeun9** [comment]
Oh Sorry @jespa007! You have to add your domain in whitlist(it is at the right bottom in your screenshot).

**Comment by jespa007** [comment]
@YongEun-vc I've added https://bgaze.com at Whitelist 

![image](https://user-images.githubusercontent.com/7852409/120177581-dee4de00-c208-11eb-9818-cbf4b8146287.png)


but stills I get the CORS policy,

![image](https://user-images.githubusercontent.com/7852409/120177698-f9b75280-c208-11eb-9ef1-aa9387334e4e.png)

As you can see there's an aditional error that it the websocket cannot start at 61366. And this is because I have a virtual machine that only allow a set of ports be opened. This error could be also related about CORS policy issue ? If is that, could you tell in which range of ports this websocket will connect ?

**Comment by leeyongeun9** [comment]
@jespa007 Sorry for having problem with our sdk.
There seems to be a problem in the handling of the [https://domain:port] format address in the Cors exception handling function.

For your current development process, use the **IP address and Dev key**.
The above issue will be resolved soon.

**Comment by jespa007** [comment]
@YongEun-vc but with development key I cannot test the app on mobile or tablet... except a surface that in this case it has a windows and I can install nodejs and the all required packages.

**Comment by leeyongeun9** [comment]
@jespa007 
First of all, the SeeSo Web SDK officially support some desktop web browsers now.
The SDK does not work on mobile browsers because some necessary features are not implemented on them. 
Only in android chrome, we have recently confirmed that SDK works with low performance.

And also, could you tell me what is difference between using the 'Dev' key and the 'Prod" key when using it on mobile or table?

**Comment by jespa007** [comment]
@YongEun-vc it should be enough for us run an app using Seeso Web SDK in android with chrome. To do that I have to run a the public server that inits Seeso Web SDK API with product key that matches with withlist url (in our case https://bgaze.com). So, after that, I guess I can open a browser in a android mobile an run the App with Seeso Web SDK initilized succesfully.

About the difference betwen usign dev and prod key is that, according I've readed in this thread, using dev key it only runs Seeso in localhost environment and the server is only visible locally in my laptop. I cannot launch another device as a client to try Seeso Web SDK using  my laptop as a server.

**Comment by leeyongeun9** [comment]
Oh sorry @jespa007 
We intended to enable access using **Public IP address as well as localhost** if a developer uses the Dev key.
However, when I check it now, it seems that the part about the public IP address does not work properly.
I'll fix this part quickly and let you know.

**Comment by jespa007** [comment]
@YongEun-vc  thanks. We'll wait for fix this then :+1:

**Comment by leeyongeun9** [comment]
@jespa007 We fixed the problems.
All cases that I mentioned will work fine.
1. production key + domain (+ port number)
2. development key + localhost (+ port number)
3. development key + public ip (+ port number)

**Comment by jespa007** [comment]
@YongEun-vc I've try it and it works! Thanks for fix it!
