### ISSUE TITLE
 Bring SeesoWeb for client side only

### ISSUE THREAD

**Issue by jespa007** [visualcamp/seeso-sample-web#3]
It should be great to bring SeesoWeb for client side only, i.e load your SeesoWeb API in my index.html like this,

`<script src="https://console.sesso.io/sesoo.js">`

Running Nodejs Parcel per application is not practical and also it consumes more resources in a server side

**Comment by leeyongeun9** [comment]
Hi @jespa007 
The SDK only works on client side already, the only part of SDK communicate with server is authentication.
The 'Nodejs Parcel' you mentioned is maybe this part of our server.
We have to count usage number of developers license key for commercial, so the 'Parcel' is necessary for server.

If you need client only authentication sdk, please contact us via email (business@seeso.io).
There have to be additional support for the local authentication because that is not a general plan feature.

**Comment by jespa007** [comment]
@YongEun-vc  The client only authentication  could be very useful for us.  One thing... Why is not a general plan feature ? Setting client only it requires less setup is quite quick to show people how Seeso it works. My point of view is that this feature it would benefit to you.

**Comment by leeyongeun9** [comment]
@jespa007 The client only authentication will prevent us from measuring the number of activated sessions so that we cannot charge anything. 
Therefore, in order to use local authentication, there must be an agreement in any form, such as whether you and us sign a contract, talk to each other about the plan for use of seeso and pay the cost in advance.

**Comment by jespa007** [comment]
@YongEun-vc thanks. We'll do that :+1:
